name: Code Review Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier Formatter
        run: npm run format

      - name: Run Linter
        run: npm run lint
